import React, { useMemo, useState, useRef, useEffect } from "react";
import "./index.css";

export default function App() {
  const [isLayoutOpen, setIsLayoutOpen] = useState(false);
  const [extraCards, setExtraCards] = useState([]);
  const [isPostLayoutOpen, setIsPostLayoutOpen] = useState(false);
  const [selectedPost, setSelectedPost] = useState(null);
  const [isOverviewLayoutOpen, setIsOverviewLayoutOpen] = useState(false);
  // Overview editable state
  const [ovTitle, setOvTitle] = useState("Overview:");
  const [ovPlatforms, setOvPlatforms] = useState("Instagram, X");
  const [ovVoice, setOvVoice] = useState("Warm, honest");
  const [ovTargets, setOvTargets] = useState([
    "Young professionals (20–30)",
    "Morning ritual lovers",
    "Aesthetic lifestyle followers",
  ]);
  // New Post Editor state
  const [postCaption, setPostCaption] = useState("");
  const [postTitle, setPostTitle] = useState("");
  const [postDate, setPostDate] = useState("");
  const [postPlatform, setPostPlatform] = useState("Instagram");
  const [postTags, setPostTags] = useState("soft light, warm tone");
  const [mediaPreviewUrl, setMediaPreviewUrl] = useState("");
  // Default posts media overrides (for Facebook / Instagram / Reels)
  const [fbMediaUrl, setFbMediaUrl] = useState("");
  const [igMediaUrl, setIgMediaUrl] = useState("");
  const [reelsMediaUrl, setReelsMediaUrl] = useState("");
  // Default posts title/date (shown on main viewport)
  const [fbTitle, setFbTitle] = useState("Facebook post");
  const [fbDate, setFbDate] = useState("September 26 2024");
  const [igTitle, setIgTitle] = useState("Instagram post");
  const [igDate, setIgDate] = useState("October 19, 2024");
  const [reelsTitle, setReelsTitle] = useState("Instagram reels draft");
  const [reelsDate, setReelsDate] = useState("November 15, 2025");
  // refs for auto-resize
  const postCaptionRef = useRef(null);
  const newCaptionRef = useRef(null);
  const fbDefaultCaption =
    "The city hasn’t quite woken up yet.\n Light spills across the table, catching on the edge of the plate —\n  crisp folds, melting cream, a trace of chocolate still soft from the heat.\nThere’s something about quiet breakfasts that feels like a secret —\n  the world breathing slower,\n  a small reward for being here early.\nMaybe it’s not about coffee or pastries at all,\n  but about finding warmth before the day starts.\nStay for the second cup. ☕\n(all the sentences here is generated by ChatGPT here for insturction used)";
  const fbAnalysisText =
    "Tone Consistency: 92% — Strongly matches “Warm & Honest” campaign tone\n" +
    "Vibe Cluster: “Morning Rituals / Soft Light / Minimal Props”\n" +
    "Detected Mood: Calm · Intimate · Reflective";
  const fbFeedbackText =
    "This reads 90% on-brand for the “City Mornings” series.\n\n" +
    "Keep the tactile imagery (“first quiet bite”).\n\n" +
    "Try ending with a subtle invitation: “Stay for the second cup.”\n\n" +
    "🎯 Target Audience Match   Segment      Engagement    Fit     Notes\n" +
    "Young Professionals (20–30)  ✅ High     Tone resonates with weekday calm\n" +
    "Morning Ritual Lovers        ✅ High     Good sensory trigger\n" +
    "Aesthetic Lifestyle Followers ⚠️ Medium Could add more visual adjectives";

  // auto-resize textareas
  useEffect(() => {
    if (isPostLayoutOpen && postCaptionRef.current) {
      const el = postCaptionRef.current;
      el.style.height = "auto";
      el.style.height = el.scrollHeight + "px";
    }
  }, [postCaption, isPostLayoutOpen]);
  useEffect(() => {
    if (isLayoutOpen && newCaptionRef.current) {
      const el = newCaptionRef.current;
      el.style.height = "auto";
      el.style.height = el.scrollHeight + "px";
    }
  }, [postCaption, isLayoutOpen]);

  // (Removed previous highlight attempt placeholder)
  // Posted flags
  const [fbPosted, setFbPosted] = useState(false);
  const [igPosted, setIgPosted] = useState(false);
  const [reelsPosted, setReelsPosted] = useState(false);
  // Default pens can also be dragged to delete
  const [defaultPens, setDefaultPens] = useState({
    black: { baseX: 65, dx: 0, dy: 0, removed: false },
    white: { baseX: 150, dx: 0, dy: 0, removed: false },
    yellow: { baseX: -40, dx: 0, dy: 0, removed: false },
  });
  // AI Vibe loading (placeholder - will be replaced by API)
  const [isVibeLoading, setIsVibeLoading] = useState(false);
  const vibeTimerRef = useRef(null);
  const [selectedPen, setSelectedPen] = useState(null);
  const [pens, setPens] = useState([]);
  const penCycle = ["black", "white", "yellow"];
  const [rubberActive, setRubberActive] = useState(false); // Eraser target highlight state
  // Modal states for add/delete pen
  const [isAddPenModalOpen, setIsAddPenModalOpen] = useState(false);
  const [newPenName, setNewPenName] = useState("");
  const [isDeleteConfirmOpen, setIsDeleteConfirmOpen] = useState(false);
  const [pendingDeletePen, setPendingDeletePen] = useState(null);

  function handleMediaChange(e) {
    const file = e.target.files && e.target.files[0];
    if (file) {
      const url = URL.createObjectURL(file);
      setMediaPreviewUrl(url);
    }
  }

  const vibeColors = useMemo(() => {
    const t = (postTags || "").toLowerCase();
    if (t.includes("warm") || t.includes("beige")) {
      return ["#EADAC5", "#FCF9F3", "#C7B8A1"];
    }
    if (t.includes("playful") || t.includes("pink")) {
      return ["#FFE4EC", "#FAD1E1", "#F7A8C0"];
    }
    if (t.includes("calm") || t.includes("soft")) {
      return ["#DCE7F2", "#EFF5FA", "#B6C7DA"];
    }
    return postPlatform === "TikTok"
      ? ["#111111", "#2EC4B6", "#FF1C6B"]
      : ["#E6F3F0", "#29967F", "#475272"];
  }, [postTags, postPlatform]);

  const aiFeedback = useMemo(() => {
    const len = postCaption.trim().length || 10;
    const pct = Math.min(97, 75 + ((len % 18) + 6));
    return `${pct}% on-brand, try adding a sensory detail.`;
  }, [postCaption]);

  function handleSavePost() {
    const dateLabel = postDate
      ? new Date(postDate).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })
      : new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
    const newCard = {
      id: Date.now(),
      kind: "extra",
      title: postTitle
        ? postTitle
        : postCaption
        ? (postCaption.length > 28 ? postCaption.slice(0, 28) + "…" : postCaption)
        : `${postPlatform} post`,
      date: dateLabel,
      mediaUrl: mediaPreviewUrl || "",
      caption: postCaption || "",
      posted: false,
    };
    setExtraCards((prev) => [...prev, newCard]);
    setIsLayoutOpen(false);
  }
  function toISODate(display) {
    if (!display) return "";
    const d = new Date(display);
    if (isNaN(d.getTime())) return "";
    const yyyy = d.getFullYear();
    const mm = String(d.getMonth() + 1).padStart(2, "0");
    const dd = String(d.getDate()).padStart(2, "0");
    return `${yyyy}-${mm}-${dd}`;
  }
  function handleOpenPost(card) {
    setSelectedPost(card || null);
    // Pre-fill: title/date/platform/media
    if (card?.kind === "facebook") {
      setPostTitle(fbTitle);
      setPostDate(toISODate(fbDate));
      setPostPlatform("Facebook");
      setMediaPreviewUrl(fbMediaUrl || "");
      setPostCaption(card?.caption || fbDefaultCaption); // Only Facebook uses the default caption
    } else if (card?.kind === "instagram") {
      setPostTitle(igTitle);
      setPostDate(toISODate(igDate));
      setPostPlatform("Instagram");
      setMediaPreviewUrl(igMediaUrl || "");
      setPostCaption(card?.caption || ""); // For non-Facebook: use saved or empty
    } else if (card?.kind === "reels") {
      setPostTitle(reelsTitle);
      setPostDate(toISODate(reelsDate));
      setPostPlatform("Instagram"); // Reels is within IG system
      setMediaPreviewUrl(reelsMediaUrl || "");
      setPostCaption(card?.caption || ""); // For non-Facebook: use saved or empty
    } else if (card) {
      setPostTitle(card.title || "");
      setPostDate(toISODate(card.date || ""));
      setPostPlatform(card.platform || "Instagram");
      setMediaPreviewUrl(card.mediaUrl || "");
      setPostCaption(card.caption || ""); // Other cards use their own caption
    }
    setIsPostLayoutOpen(true);
    // Trigger one-time loading animation when opening
    setIsVibeLoading(true);
    setTimeout(() => setIsVibeLoading(false), 1200);
  }
  function handleCaptionChange(e) {
    setPostCaption(e.target.value);
    if (isPostLayoutOpen && postPlatform === "Facebook") {
      setIsVibeLoading(true);
      if (vibeTimerRef.current) clearTimeout(vibeTimerRef.current);
      vibeTimerRef.current = setTimeout(() => setIsVibeLoading(false), 900);
    }
  }
  function addNewPenPrompt() {
    setIsAddPenModalOpen(true);
  }
  function confirmAddPen() {
    if (!newPenName.trim()) return;
    addNewPen(newPenName.trim());
    setNewPenName("");
    setIsAddPenModalOpen(false);
  }
  function cancelAddPen() {
    setNewPenName("");
    setIsAddPenModalOpen(false);
  }
  function addNewPen(label) {
    const nextColor = penCycle[pens.length % penCycle.length];
    const src =
      nextColor === "black"
        ? "/assert/black_pen.png"
        : nextColor === "white"
        ? "/assert/white_pen.png"
        : "/assert/yellow_pen.png";
    // Set base X position based on color to match current CSS
    const baseX = 
      nextColor === "black" ? 65 :   // matches CSS .black-pen-box --base
      nextColor === "white" ? 150 :  // matches CSS .white-pen-box --base
      -40;                           // matches CSS .yellow-pen-box --base
    const newPen = {
      id: `pen_${Date.now()}`,
      color: nextColor,
      src,
      label,
      baseX,
      entering: true,
      ready: false,
      dragX: 0,
    };
    setPens((prev) => [...prev, newPen]);
    requestAnimationFrame(() => {
      setPens((prev) =>
        prev.map((p) =>
          p.id === newPen.id ? { ...p, entering: false, ready: true } : p
        )
      );
    });
  }
  function handlePostModalSave() {
    // If not editing an existing card (future: might use selectedPost == null for new posts)
    if (!selectedPost) {
      handleSavePost();
    }
    // Edit existing content: save image to corresponding source
    const dateLabel = postDate
      ? new Date(postDate).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })
      : "";
    if (selectedPost?.kind === "extra" && selectedPost.id) {
      setExtraCards((prev) =>
        prev.map((c) =>
          c.id === selectedPost.id
            ? { ...c, mediaUrl: mediaPreviewUrl || c.mediaUrl, title: postTitle || c.title, date: dateLabel || c.date }
            : c
        )
      );
    } else if (selectedPost?.kind === "facebook") {
      if (mediaPreviewUrl) setFbMediaUrl(mediaPreviewUrl);
      if (postTitle) setFbTitle(postTitle);
      if (dateLabel) setFbDate(dateLabel);
    } else if (selectedPost?.kind === "instagram") {
      if (mediaPreviewUrl) setIgMediaUrl(mediaPreviewUrl);
      if (postTitle) setIgTitle(postTitle);
      if (dateLabel) setIgDate(dateLabel);
    } else if (selectedPost?.kind === "reels") {
      if (mediaPreviewUrl) setReelsMediaUrl(mediaPreviewUrl);
      if (postTitle) setReelsTitle(postTitle);
      if (dateLabel) setReelsDate(dateLabel);
    }
    setIsPostLayoutOpen(false);
  }
  function startDrag(e, id) {
    e.preventDefault();
    const startX = e.clientX;
    const startY = e.clientY;
    function onMove(ev) {
      const dx = ev.clientX - startX;
      const dy = ev.clientY - startY;
      setPens((prev) => prev.map((p) => (p.id === id ? { ...p, dragX: dx, dragY: dy } : p)));
      // Detect if dragging near eraser area (lower left of screen)
      const nearRubber = ev.clientY > window.innerHeight * 0.55 && ev.clientX < 520;
      setRubberActive(nearRubber);
    }
    function onUp(ev) {
      document.removeEventListener("mousemove", onMove);
      document.removeEventListener("mouseup", onUp);
      const pen = pens.find((p) => p.id === id);
      if (!pen) return;
      // Check if released in eraser area
      const nearRubber = ev.clientY > window.innerHeight * 0.55 && ev.clientX < 520;
      if (nearRubber) {
        setPendingDeletePen(pen);
        setIsDeleteConfirmOpen(true);
        setPens((prev) => prev.map((p) => (p.id === id ? { ...p, dragX: 0, dragY: 0 } : p)));
      } else {
        setPens((prev) => prev.map((p) => (p.id === id ? { ...p, dragX: 0, dragY: 0 } : p)));
      }
      setRubberActive(false);
    }
    document.addEventListener("mousemove", onMove);
    document.addEventListener("mouseup", onUp);
  }
  function confirmDeletePen() {
    if (!pendingDeletePen) return;
    if (pendingDeletePen.kind === "default" && pendingDeletePen.key) {
      // Delete default pen
      const key = pendingDeletePen.key;
      setDefaultPens((prev) => ({ ...prev, [key]: { ...prev[key], removed: true } }));
    } else {
      // Delete new pen
      setPens((prev) => prev.map((p) => (p.id === pendingDeletePen.id ? { ...p, removing: true } : p)));
      setTimeout(() => setPens((prev) => prev.filter((p) => p.id !== pendingDeletePen.id)), 280);
    }
    setPendingDeletePen(null);
    setIsDeleteConfirmOpen(false);
  }
  function cancelDeletePen() {
    setPendingDeletePen(null);
    setIsDeleteConfirmOpen(false);
  }
  // Drag-to-delete for default pens
  function startDragDefault(e, key) {
    e.preventDefault();
    const startX = e.clientX;
    const startY = e.clientY;
    function onMove(ev) {
      const dx = ev.clientX - startX;
      const dy = ev.clientY - startY;
      setDefaultPens((prev) => ({ ...prev, [key]: { ...prev[key], dx, dy } }));
      const nearRubber = ev.clientY > window.innerHeight * 0.55 && ev.clientX < 520;
      setRubberActive(nearRubber);
    }
    function onUp(ev) {
      document.removeEventListener("mousemove", onMove);
      document.removeEventListener("mouseup", onUp);
      const nearRubber = ev.clientY > window.innerHeight * 0.55 && ev.clientX < 520;
      if (nearRubber) {
        // Use custom modal instead of system confirm
        const labelMap = { black: "OOTD Check", white: "Product Review", yellow: "Tutorial" };
        setPendingDeletePen({ kind: "default", key, label: labelMap[key] || "This vibe" });
        setIsDeleteConfirmOpen(true);
      }
      // Reset visual displacement anyway
      setDefaultPens((prev) => ({ ...prev, [key]: { ...prev[key], dx: 0, dy: 0 } }));
      setRubberActive(false);
    }
    document.addEventListener("mousemove", onMove);
    document.addEventListener("mouseup", onUp);
  }
  function handlePostNow() {
    if (selectedPost?.kind === "facebook") {
      setFbPosted(true);
    } else if (selectedPost?.kind === "instagram") {
      setIgPosted(true);
    } else if (selectedPost?.kind === "reels") {
      setReelsPosted(true);
    } else if (selectedPost?.kind === "extra" && selectedPost?.id) {
      setExtraCards((prev) => prev.map((c) => (c.id === selectedPost.id ? { ...c, posted: true } : c)));
    }
    setIsPostLayoutOpen(false); /* Return to main interface */
  }
  return (
    <div className="min-h-screen flex items-center justify-center bg-paper">
      <div className="pen-images-container">
        {!defaultPens.black.removed && (
        <div
          className={`pen-box black-pen-box ${selectedPen === "black" ? "selected" : ""} ${defaultPens.black.dx || defaultPens.black.dy ? "dragging" : ""}`}
          onClick={() => setSelectedPen("black")}
          onMouseDown={(e) => startDragDefault(e, "black")}
          style={{
            "--base": `${defaultPens.black.baseX}px`,
            transform:
              defaultPens.black.dx || defaultPens.black.dy
                ? `translate(${defaultPens.black.baseX + defaultPens.black.dx}px, ${defaultPens.black.dy}px)`
                : undefined,
          }}
        >
          <img src="/assert/black_pen.png" alt="black pen" className="pen-image" />
          <span className="pen-text">OOTD Check</span>
        </div>
        )}
        {!defaultPens.white.removed && (
        <div
          className={`pen-box white-pen-box ${selectedPen === "white" ? "selected" : ""} ${defaultPens.white.dx || defaultPens.white.dy ? "dragging" : ""}`}
          onClick={() => setSelectedPen("white")}
          onMouseDown={(e) => startDragDefault(e, "white")}
          style={{
            "--base": `${defaultPens.white.baseX}px`,
            transform:
              defaultPens.white.dx || defaultPens.white.dy
                ? `translate(${defaultPens.white.baseX + defaultPens.white.dx}px, ${defaultPens.white.dy}px)`
                : undefined,
          }}
        >
          <img src="/assert/white_pen.png" alt="white pen" className="pen-image" />
          <span className="pen-text">Product Review</span>
        </div>
        )}
        {!defaultPens.yellow.removed && (
        <div
          className={`pen-box yellow-pen-box ${selectedPen === "yellow" ? "selected" : ""} ${defaultPens.yellow.dx || defaultPens.yellow.dy ? "dragging" : ""}`}
          onClick={() => setSelectedPen("yellow")}
          onMouseDown={(e) => startDragDefault(e, "yellow")}
          style={{
            "--base": `${defaultPens.yellow.baseX}px`,
            transform:
              defaultPens.yellow.dx || defaultPens.yellow.dy
                ? `translate(${defaultPens.yellow.baseX + defaultPens.yellow.dx}px, ${defaultPens.yellow.dy}px)`
                : undefined,
          }}
        >
          <img src="/assert/yellow_pen.png" alt="yellow pen" className="pen-image" />
          <span className="pen-text tutorial-text">Tutorial</span>
        </div>
        )}
        {/* New pens should appear above ADD NEW, so pens.map comes before ADD NEW */}
        {pens.map((p) => {
          const isDragging = (p.dragX !== 0 || p.dragY !== 0);
          return (
            <div
              key={p.id}
              className={`pen-box ${p.entering ? "entering" : ""} ${p.ready ? "ready" : ""} ${p.removing ? "removing" : ""} ${selectedPen === p.id ? "selected" : ""} ${isDragging ? "dragging" : ""}`}
              style={{ 
                "--base": `${p.baseX}px`, 
                transform: isDragging 
                  ? `translate(${p.baseX + (p.dragX || 0)}px, ${p.dragY || 0}px)` 
                  : undefined 
              }}
              onClick={() => setSelectedPen(p.id)}
              onMouseDown={(e) => startDrag(e, p.id)}
            >
              <img src={p.src} alt={`${p.color} pen`} className="pen-image" />
              <span className="pen-text">{p.label}</span>
            </div>
          );
        })}
        <div className="pen-box pencil-box" onClick={() => addNewPenPrompt()}>
          <img src="/assert/pencil.png" alt="pencil" className="pen-image" />
          <span className="pen-text">ADD NEW</span>
        </div>
        <div className={`pen-box rubber-box ${rubberActive ? "rubber-active" : ""}`}>
          <img src="/assert/rubber.png" alt="rubber" className="rubber-image" />
          <span className="pen-text remove-vibe-text">Drag here to delete</span>
        </div>
      </div>

      {/* Tutorial Board */}
      <div className="tutorial-wrapper">
        {/* Pin (moved out of board) */}
        <img src="/assert/pin.png" alt="pin" className="pin-icon" />

        <div className="tutorial-board">
          {/* Title */}
          <h1 className="tutorial-title">Tutorial</h1>
        

        {/* Overview Section */}
        <div className="overview-section" onClick={() => setIsOverviewLayoutOpen(true)}>
          <h2 className="overview-title">
            {ovTitle}
          </h2>
          <div className="overview-content">
            <p className="overview-item">
              <span className="overview-label">Platforms:</span>{" "}
              <span className="editable-inline">{ovPlatforms}</span>
            </p>
            <p className="overview-item">
              <span className="overview-label">Brand Voice:</span>{" "}
              <span className="editable-inline">{ovVoice}</span>
            </p>
            <p className="overview-item">
              <span className="overview-label">Target Audience:</span>
            </p>
            <ul className="target-list">
              {ovTargets.map((t, i) => (
                <li key={i} className="editable-inline">{t}</li>
              ))}
            </ul>
          </div>
        </div>

        

        {/* Post Cards */}
        <div className="posts-container">
          {/* Facebook post card */}
          <div className="post-card x-post" tabIndex={0} onClick={() => handleOpenPost({ kind: "facebook", title: fbTitle, date: fbDate })}>
            <img src="/assert/tape1.png" alt="tape" className="card-tape" />
            <img src="/assert/frame.png" alt="frame" className="card-frame" />
            {fbMediaUrl ? (
              <div className="extra-photo" style={{ backgroundImage: `url(${fbMediaUrl})` }}></div>
            ) : (
              <div className="photo-placeholder"></div>
            )}
            {fbPosted && <img src="/assert/pst.png" alt="posted" className="post-stamp-img" />}
            <p className="post-type">{fbTitle}</p>
            <p className="post-date">{fbDate}</p>
          </div>

          {/* Instagram post card */}
          <div className="post-card instagram-post" tabIndex={0} onClick={() => handleOpenPost({ kind: "instagram", title: igTitle, date: igDate })}>
            <img src="/assert/tape2.png" alt="tape" className="card-tape" />
            <img src="/assert/frame.png" alt="frame" className="card-frame" />
            {igMediaUrl ? (
              <div className="extra-photo" style={{ backgroundImage: `url(${igMediaUrl})` }}></div>
            ) : (
              <div className="photo-placeholder"></div>
            )}
            {igPosted && <img src="/assert/pst.png" alt="posted" className="post-stamp-img" />}
            <p className="post-type">{igTitle}</p>
            <p className="post-date">{igDate}</p>
          </div>

          {/* Instagram reels draft */}
          <div className="post-card reels-draft" tabIndex={0} onClick={() => handleOpenPost({ kind: "reels", title: reelsTitle, date: reelsDate })}>
            <img src="/assert/tape1.png" alt="tape" className="card-tape" />
            <img src="/assert/frame.png" alt="frame" className="card-frame" />
            {reelsMediaUrl ? (
              <div className="extra-photo" style={{ backgroundImage: `url(${reelsMediaUrl})` }}></div>
            ) : (
              <div className="photo-placeholder"></div>
            )}
            {reelsPosted && <img src="/assert/pst.png" alt="posted" className="post-stamp-img" />}
            <p className="post-type">{reelsTitle}</p>
            <p className="post-date">{reelsDate}</p>
          </div>

          {/* Extra cards appended */}
          {extraCards.map((card, idx) => (
            <div
              key={card.id}
              className={`post-card new-campaign-card ${idx === extraCards.length - 1 ? "latest-campaign" : ""}`}
              tabIndex={0}
              onClick={() => handleOpenPost({ ...card, kind: "extra" })}
            >
              <img src="/assert/tape2.png" alt="tape" className="card-tape" />
              <img src="/assert/frame.png" alt="frame" className="card-frame" />
              {card.mediaUrl ? (
                <div className="extra-photo" style={{ backgroundImage: `url(${card.mediaUrl})` }}></div>
              ) : (
                <div className="photo-placeholder"></div>
              )}
              {card.posted && <img src="/assert/pst.png" alt="posted" className="post-stamp-img" />}
              <p className="post-type">{card.title}</p>
              <p className="post-date">{card.date}</p>
            </div>
          ))}

        </div>

          {/* Add more card - bottom right corner */}
          <div className="post-card add-more-card" onClick={() => setIsLayoutOpen(true)}>
            <p className="add-more-text">Add more?</p>
          </div>

          {/* Arrows removed per design */}
        </div>
      </div>
      {isLayoutOpen && (
        <div className="layout-overlay" onClick={() => setIsLayoutOpen(false)}>
          <div className="layout-modal" onClick={(e) => e.stopPropagation()}>
            <div className="layout-canvas">
              <div className="layout-safe">
                <div className="layout-panel">
                <div className="layout-form">
                  <div className="field">
                    <label>Title</label>
                    <input value={postTitle} onChange={(e) => setPostTitle(e.target.value)} placeholder="Post title (optional)" />
                  </div>
                  <div className="field">
                    <label>Caption</label>
                      <textarea
                        ref={newCaptionRef}
                        rows={1}
                        value={postCaption}
                        onChange={(e) => setPostCaption(e.target.value)}
                        placeholder="Write something cozy and on-brand..."
                      />
                  </div>
                  <div className="field">
                    <label>Date</label>
                    <input type="date" value={postDate} onChange={(e) => setPostDate(e.target.value)} />
                  </div>
                  <div className="field">
                    <label>Photo</label>
                    <div className="row">
                      <input type="file" accept="image/*" onChange={handleMediaChange} />
                      {mediaPreviewUrl && <img className="media-thumb" src={mediaPreviewUrl} alt="preview" />}
                    </div>
                  </div>
                  <div className="field">
                    <label>Platform</label>
                    <div className="row">
                      {["Instagram", "TikTok", "Facebook"].map((p) => (
                        <label key={p} className="radio">
                          <input type="radio" name="platform" value={p} checked={postPlatform === p} onChange={(e) => setPostPlatform(e.target.value)} />
                          <span>{p}</span>
                        </label>
                      ))}
                    </div>
                  </div>
                  <div className="field">
                    <label>Visual Tags</label>
                    <input value={postTags} onChange={(e) => setPostTags(e.target.value)} placeholder="soft light, warm tone" />
                    <div className="chips">
                      {(postTags || "").split(",").filter(Boolean).slice(0, 6).map((t, i) => (
                        <span key={i} className="pill">{t.trim()}</span>
                      ))}
                    </div>
                  </div>
                </div>
                  <div className="layout-preview">
                  <div className="media-title">Media preview</div>
                  {/*Platform-specific preview */}
                  {(() => {
                    const platformClass =
                      postPlatform === "TikTok"
                        ? "platform-tiktok"
                        : postPlatform === "Facebook"
                        ? "platform-facebook"
                        : "platform-instagram";
                    return (
                      <div className={`post-sim-card ${platformClass}`}>
                        {postPlatform === "Facebook" && (
                          <div className="fb-header">
                            <div className="avatar"></div>
                            <div className="fb-meta">
                              <div className="name">You</div>
                              <div className="time">{postDate || "Just now"}</div>
                            </div>
                            <div className="fb-share">↗</div>
                          </div>
                        )}
                        
                        <div className="post-media" style={{ backgroundImage: mediaPreviewUrl ? `url(${mediaPreviewUrl})` : "none" }}>
                          {!mediaPreviewUrl && <div className="media-empty"></div>}
                        </div>
                        
                        <div className="post-caption-preview">
                          <strong>{postTitle || "Post title…"}</strong>
                          <div>{postCaption || "Write a cozy caption here..."}</div>
                          <div className="post-date-preview">{postDate || ""}</div>
                        </div>
                        {/* Tags preview */}
                        <div className="post-tags-preview">
                          {(postTags || "")
                            .split(",")
                            .filter(Boolean)
                            .slice(0, 6)
                            .map((t, i) => (
                              <span key={i} className="pill">{t.trim()}</span>
                            ))}
                        </div>
                      </div>
                    );
                  })()}
                  <div className="ai-feedback">{aiFeedback}</div>
                  <div className="vibe-palette">
                    {vibeColors.map((c) => (
                      <span key={c} style={{ background: c }}></span>
                    ))}
                  </div>
                  <div className="vibe-note">These swatches are a vibe palette inferred from your Visual Tags and platform, and they update live as you type.</div>
                </div>
                </div>
              </div>
            </div>
          </div>
          <div className="layout-cta-right" onClick={(e) => e.stopPropagation()}>
            <button className="btn-ghost" onClick={() => setIsLayoutOpen(false)}>Cancel</button>
            <button className="btn-primary" onClick={handleSavePost}>Save Post</button>
          </div>
        </div>
      )}
      {isOverviewLayoutOpen && (
        <div className="layout-overlay" onClick={() => setIsOverviewLayoutOpen(false)}>
          <div className="layout-modal" onClick={(e) => e.stopPropagation()}>
            <div className="layout-canvas overview-canvas">
              <div className="layout-safe overview-safe">
                <div className="layout-panel overview-panel">
                  <h3 className="media-title edit-vibe-title">EDIT VIBE</h3>
                  <div className="layout-form" style={{ maxHeight: "unset", overflow: "visible" }}>
                    <div className="field">
                      <label>Title</label>
                      <input value={ovTitle} onChange={(e) => setOvTitle(e.target.value)} />
                    </div>
                    <div className="field">
                      <label>Platforms</label>
                      <input value={ovPlatforms} onChange={(e) => setOvPlatforms(e.target.value)} />
                    </div>
                    <div className="field">
                      <label>Brand Voice</label>
                      <input value={ovVoice} onChange={(e) => setOvVoice(e.target.value)} />
                    </div>
                    <div className="field">
                      <label>Target Audience (3 lines)</label>
                      {ovTargets.map((t, i) => (
                        <input
                          key={i}
                          value={t}
                          onChange={(e) => {
                            const next = [...ovTargets];
                            next[i] = e.target.value;
                            setOvTargets(next);
                          }}
                          style={{ marginBottom: 8 }}
                        />
                      ))}
                    </div>
                    <div className="actions">
                      <button className="btn-ghost" onClick={() => setIsOverviewLayoutOpen(false)}>Cancel</button>
                      <button className="btn-primary" onClick={() => setIsOverviewLayoutOpen(false)}>Save</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
      {isPostLayoutOpen && (
        <div className="layout-overlay" onClick={() => setIsPostLayoutOpen(false)}>
          <div className="layout-modal" onClick={(e) => e.stopPropagation()}>
            <div className="layout-canvas">
              <div className="layout-safe" style={{ transform: "translate(-16px, -12px)" }}>
                <div className="layout-panel" style={{ display: "block", padding: "12px" }}>
                  {/* Form structure matching Add more (input section only) */}
                  <div className="layout-form">
                    {/* Platform at top (read-only small rectangle display) */}
                    <div className="field">
                      <label>Platform</label>
                      <div className="platform-pill" title="Platform cannot be changed here">
                        {postPlatform}
                      </div>
                    </div>
                    {/* Photo second: display large preview first, then file selection */}
                    <div className="field">
                      <label>Photo</label>
                      {(() => {
                        const t = (selectedPost?.title || "").toLowerCase();
                        const fallback =
                          /reel/.test(t)
                            ? "/assert/placeholder_3.jpeg"
                            : /instagram/.test(t)
                            ? "/assert/placeholder_2.jpeg"
                            : /facebook/.test(t)
                            ? "/assert/placholder_1.jpeg"
                            : "";
                        const previewUrl = mediaPreviewUrl || selectedPost?.mediaUrl || fallback;
                        const ratio =
                          postPlatform === "TikTok"
                            ? "16 / 9"
                            : postPlatform === "Facebook"
                            ? "1.91 / 1"
                            : "1 / 1"; // Instagram square
                        return (
                          <div
                            className="media-large"
                            style={{ backgroundImage: previewUrl ? `url(${previewUrl})` : "none", aspectRatio: ratio }}
                          >
                            {!previewUrl && <div className="media-empty"></div>}
                          </div>
                        );
                      })()}
                      <input className="grow" type="file" accept="image/*" onChange={handleMediaChange} />
                    </div>
                    <div className="field">
                      <label>Title</label>
                      <input value={postTitle} onChange={(e) => setPostTitle(e.target.value)} placeholder="Post title…" />
                    </div>
                    <div className="field">
                      <label>Caption</label>
                      <textarea
                        ref={postCaptionRef}
                        className="caption-large"
                        rows={1}
                        value={postCaption}
                        onChange={handleCaptionChange}
                        placeholder="Write a cozy caption here..."
                      />
                    </div>
                    <div className="field">
                      <label>Date</label>
                      <input type="date" value={postDate} onChange={(e) => setPostDate(e.target.value)} />
                    </div>
                    <div className="field">
                      <label>Visual Tags</label>
                      <input value={postTags} onChange={(e) => setPostTags(e.target.value)} placeholder="soft light, warm tone" />
                      <div className="chips">
                        {(postTags || "").split(",").filter(Boolean).slice(0, 6).map((t, i) => (
                          <span key={i} className="pill">{t.trim()}</span>
                        ))}
                      </div>
                    </div>
                    {/* AI Vibe Analysis and Feedback (Facebook only shows example, API integration to follow) */}
                    {postPlatform === "Facebook" && (
                      <>
                        <div className="field">
                          <label>AI Vibe Analysis:</label>
                          <div className={`ai-vibe-box left ${isVibeLoading ? "loading" : ""}`}>
                            {isVibeLoading ? (
                              <div className="spinner" />
                            ) : (
                              <pre className="ai-pre">{fbAnalysisText}</pre>
                            )}
                          </div>
                        </div>
                        <div className="field">
                          <label>AI Feedback:</label>
                          <div className={`ai-vibe-box left ${isVibeLoading ? "loading" : ""}`}>
                            {isVibeLoading ? (
                              <div className="spinner" />
                            ) : (
                              <div className="ai-feedback-block">
                                <p className="ai-text">This reads 90% on-brand for the “City Mornings” series.</p>
                                <p className="ai-text">Keep the tactile imagery (“first quiet bite”).</p>
                                <p className="ai-text">Try ending with a subtle invitation: “Stay for the second cup.”</p>
                                <div className="ai-table-wrap">
                                  <table className="ai-table">
                                    <thead>
                                      <tr>
                                        <th>Target Audience</th>
                                        <th>Engagement</th>
                                        <th>Fit</th>
                                        <th>Notes</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      <tr>
                                        <td>Young Professionals (20–30)</td>
                                        <td>High</td>
                                        <td>High</td>
                                        <td>Tone resonates with weekday calm</td>
                                      </tr>
                                      <tr>
                                        <td>Morning Ritual Lovers</td>
                                        <td>High</td>
                                        <td>High</td>
                                        <td>Good sensory trigger</td>
                                      </tr>
                                      <tr>
                                        <td>Aesthetic Lifestyle Followers</td>
                                        <td>Medium</td>
                                        <td>Medium</td>
                                        <td>Could add more visual adjectives</td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </div>
                              </div>
                            )}
                          </div>
                        </div>
                      </>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* Left vertical action buttons */}
          <div className="layout-cta-left" onClick={(e) => e.stopPropagation()}>
            <button className="btn-primary" onClick={() => { setIsVibeLoading(true); setTimeout(() => setIsVibeLoading(false), 1200); }}>{`Regenerate`}</button>
            <button
              className="btn-post"
              onClick={handlePostNow}
              disabled={
                (selectedPost?.kind === "facebook" && fbPosted) ||
                (selectedPost?.kind === "instagram" && igPosted) ||
                (selectedPost?.kind === "reels" && reelsPosted)
              }
            >
              Post
            </button>
            <button className="btn-primary" onClick={handlePostModalSave}>Save Post </button>
            <button className="btn-ghost" onClick={() => setIsPostLayoutOpen(false)}>Cancel</button>
          </div>
        </div>
      )}

      {/* Add New Pen Modal */}
      {isAddPenModalOpen && (
        <div className="layout-overlay" onClick={cancelAddPen}>
          <div className="simple-modal" onClick={(e) => e.stopPropagation()}>
            <h3 className="simple-modal-title">Add New Campaign</h3>
            <input
              type="text"
              className="simple-modal-input"
              placeholder="Campaign Name"
              value={newPenName}
              onChange={(e) => setNewPenName(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && confirmAddPen()}
              autoFocus
            />
            <div className="simple-modal-actions">
              <button className="btn-ghost" onClick={cancelAddPen}>Cancel</button>
              <button className="btn-primary" onClick={confirmAddPen}>Create</button>
            </div>
          </div>
        </div>
      )}

      {/* Delete Confirmation Modal */}
      {isDeleteConfirmOpen && pendingDeletePen && (
        <div className="layout-overlay" onClick={cancelDeletePen}>
          <div className="simple-modal" onClick={(e) => e.stopPropagation()}>
            <h3 className="simple-modal-title">Delete Campaign</h3>
            <p className="simple-modal-text">
              Are you sure you want to delete <strong>"{pendingDeletePen.label}"</strong>?
              <br />
              This will remove all posts under it.
            </p>
            <div className="simple-modal-actions">
              <button className="btn-ghost" onClick={cancelDeletePen}>Cancel</button>
              <button className="btn-danger" onClick={confirmDeletePen}>Delete</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
